;[
  {
    state: "New York",
    cases: 102863,
    todayCases: 9810,
    deaths: 2935,
    todayDeaths: 397,
    active: 91042,
  },
  {
    state: "New Jersey",
    cases: 25590,
    todayCases: 0,
    deaths: 537,
    todayDeaths: 0,
    active: 25053,
  },
  {
    state: "California",
    cases: 11207,
    todayCases: 369,
    deaths: 246,
    todayDeaths: 12,
    active: 10111,
  },
  {
    state: "Michigan",
    cases: 10791,
    todayCases: 0,
    deaths: 417,
    todayDeaths: 0,
    active: 10369,
  },
  {
    state: "Florida",
    cases: 9585,
    todayCases: 577,
    deaths: 163,
    todayDeaths: 19,
    active: 9422,
  },
  {
    state: "Louisiana",
    cases: 9150,
    todayCases: 0,
    deaths: 310,
    todayDeaths: 0,
    active: 8820,
  },
  {
    state: "Massachusetts",
    cases: 8966,
    todayCases: 0,
    deaths: 154,
    todayDeaths: 0,
    active: 8802,
  },
  {
    state: "Pennsylvania",
    cases: 8420,
    todayCases: 1156,
    deaths: 102,
    todayDeaths: 12,
    active: 8280,
  },
  {
    state: "Illinois",
    cases: 7695,
    todayCases: 0,
    deaths: 157,
    todayDeaths: 0,
    active: 7536,
  },
  {
    state: "Washington",
    cases: 6585,
    todayCases: 0,
    deaths: 272,
    todayDeaths: 0,
    active: 5750,
  },
  {
    state: "Georgia",
    cases: 5831,
    todayCases: 483,
    deaths: 184,
    todayDeaths: 21,
    active: 5647,
  },
  {
    state: "Texas",
    cases: 5221,
    todayCases: 398,
    deaths: 84,
    todayDeaths: 7,
    active: 5030,
  },
  {
    state: "Connecticut",
    cases: 3824,
    todayCases: 0,
    deaths: 112,
    todayDeaths: 0,
    active: 3712,
  },
  {
    state: "Colorado",
    cases: 3728,
    todayCases: 0,
    deaths: 97,
    todayDeaths: 0,
    active: 3631,
  },
  {
    state: "Indiana",
    cases: 3437,
    todayCases: 398,
    deaths: 102,
    todayDeaths: 24,
    active: 3335,
  },
  {
    state: "Tennessee",
    cases: 3194,
    todayCases: 0,
    deaths: 32,
    todayDeaths: 0,
    active: 2942,
  },
  {
    state: "Ohio",
    cases: 2902,
    todayCases: 0,
    deaths: 81,
    todayDeaths: 0,
    active: 2821,
  },
  {
    state: "Maryland",
    cases: 2758,
    todayCases: 427,
    deaths: 42,
    todayDeaths: 6,
    active: 2557,
  },
  {
    state: "North Carolina",
    cases: 2093,
    todayCases: 70,
    deaths: 19,
    todayDeaths: 1,
    active: 2054,
  },
  {
    state: "Virginia",
    cases: 2012,
    todayCases: 306,
    deaths: 46,
    todayDeaths: 5,
    active: 1964,
  },
  {
    state: "Missouri",
    cases: 1834,
    todayCases: 0,
    deaths: 19,
    todayDeaths: 0,
    active: 1813,
  },
  {
    state: "Arizona",
    cases: 1769,
    todayCases: 171,
    deaths: 41,
    todayDeaths: 9,
    active: 1725,
  },
  {
    state: "Wisconsin",
    cases: 1730,
    todayCases: 0,
    deaths: 38,
    todayDeaths: 0,
    active: 1690,
  },
  {
    state: "South Carolina",
    cases: 1554,
    todayCases: 0,
    deaths: 31,
    todayDeaths: 0,
    active: 1523,
  },
  {
    state: "Nevada",
    cases: 1458,
    todayCases: 0,
    deaths: 38,
    todayDeaths: 0,
    active: 1420,
  },
  {
    state: "Mississippi",
    cases: 1358,
    todayCases: 181,
    deaths: 29,
    todayDeaths: 3,
    active: 1329,
  },
  {
    state: "Alabama",
    cases: 1270,
    todayCases: 9,
    deaths: 32,
    todayDeaths: 0,
    active: 1238,
  },
  {
    state: "Utah",
    cases: 1074,
    todayCases: 0,
    deaths: 7,
    todayDeaths: 0,
    active: 1067,
  },
  {
    state: "Oklahoma",
    cases: 988,
    todayCases: 109,
    deaths: 38,
    todayDeaths: 4,
    active: 949,
  },
  {
    state: "Idaho",
    cases: 891,
    todayCases: 0,
    deaths: 9,
    todayDeaths: 0,
    active: 882,
  },
  {
    state: "Oregon",
    cases: 826,
    todayCases: 0,
    deaths: 21,
    todayDeaths: 0,
    active: 805,
  },
  {
    state: "Minnesota",
    cases: 789,
    todayCases: 47,
    deaths: 22,
    todayDeaths: 4,
    active: 479,
  },
  {
    state: "Kentucky",
    cases: 770,
    todayCases: 0,
    deaths: 31,
    todayDeaths: 0,
    active: 675,
  },
  {
    state: "District Of Columbia",
    cases: 757,
    todayCases: 104,
    deaths: 15,
    todayDeaths: 3,
    active: 569,
  },
  {
    state: "Iowa",
    cases: 699,
    todayCases: 85,
    deaths: 11,
    todayDeaths: 0,
    active: 670,
  },
  {
    state: "Arkansas",
    cases: 683,
    todayCases: 0,
    deaths: 12,
    todayDeaths: 0,
    active: 621,
  },
  {
    state: "Rhode Island",
    cases: 657,
    todayCases: 0,
    deaths: 12,
    todayDeaths: 0,
    active: 645,
  },
  {
    state: "Kansas",
    cases: 552,
    todayCases: 0,
    deaths: 13,
    todayDeaths: 0,
    active: 539,
  },
  {
    state: "New Hampshire",
    cases: 479,
    todayCases: 0,
    deaths: 5,
    todayDeaths: 0,
    active: 383,
  },
  {
    state: "Maine",
    cases: 432,
    todayCases: 56,
    deaths: 9,
    todayDeaths: 2,
    active: 310,
  },
  {
    state: "New Mexico",
    cases: 403,
    todayCases: 0,
    deaths: 7,
    todayDeaths: 0,
    active: 396,
  },
  {
    state: "Delaware",
    cases: 393,
    todayCases: 0,
    deaths: 12,
    todayDeaths: 0,
    active: 332,
  },
  {
    state: "Vermont",
    cases: 338,
    todayCases: 0,
    deaths: 17,
    todayDeaths: 0,
    active: 321,
  },
  {
    state: "Hawaii",
    cases: 285,
    todayCases: 0,
    deaths: 1,
    todayDeaths: 0,
    active: 226,
  },
  {
    state: "Nebraska",
    cases: 246,
    todayCases: 0,
    deaths: 5,
    todayDeaths: 0,
    active: 241,
  },
  {
    state: "Montana",
    cases: 241,
    todayCases: 14,
    deaths: 6,
    todayDeaths: 0,
    active: 235,
  },
  {
    state: "West Virginia",
    cases: 217,
    todayCases: 0,
    deaths: 2,
    todayDeaths: 0,
    active: 215,
  },
  {
    state: "North Dakota",
    cases: 173,
    todayCases: 14,
    deaths: 3,
    todayDeaths: 0,
    active: 115,
  },
  {
    state: "South Dakota",
    cases: 165,
    todayCases: 0,
    deaths: 2,
    todayDeaths: 0,
    active: 106,
  },
  {
    state: "Wyoming",
    cases: 162,
    todayCases: 12,
    deaths: 0,
    todayDeaths: 0,
    active: 136,
  },
  {
    state: "Alaska",
    cases: 151,
    todayCases: 8,
    deaths: 3,
    todayDeaths: 0,
    active: 148,
  },
  {
    state: "Guam",
    cases: 82,
    todayCases: 0,
    deaths: 4,
    todayDeaths: 1,
    active: 71,
  },
  {
    state: "Northern Mariana Islands",
    cases: 8,
    todayCases: 0,
    deaths: 1,
    todayDeaths: 0,
    active: 7,
  },
  {
    state: "Puerto Rico",
    cases: 378,
    todayCases: 62,
    deaths: 15,
    todayDeaths: 3,
    active: 359,
  },
  {
    state: "United States Virgin Islands",
    cases: 37,
    todayCases: 7,
    deaths: 0,
    todayDeaths: 0,
    active: 8,
  },
  {
    state: "Wuhan Repatriated",
    cases: 3,
    todayCases: 0,
    deaths: 0,
    todayDeaths: 0,
    active: 3,
  },
  {
    state: "Diamond Princess Cruise",
    cases: 46,
    todayCases: 0,
    deaths: 0,
    todayDeaths: 0,
    active: 46,
  },
]
